### ISSUE TITLE
Bidirectional binding of lists

### ISSUE THREAD

**Issue by netopyr** [canoo/dolphin-platform#113]
We need to be able to define bidirectional bindings between Dolphin- and JavaFX ObervableLists.

**Comment by hendrikebbers** [comment]
I think we should discuss some points here:
Until now we decided to not create dolphin beans on the client. But by defining such an binding you need to create beans on the client.
 Let's say you have a JavaFX List ObservableList<MyTableItem> and a Dolphin Platform List ObservableList<MyTableItemBean>. Whenever you add an item to the JFX list the binding must add a new item to the DP list. By doing so you need to create the item by using the client bean manager. In addition you need to check if an item was removed from the JavaFX list. In that case you need to check if a clientBeanManager.remove() must be called.
Creating such a binding will be quite easy (I think I already had one and removed it before we merged the list bindings). But by using it a developer needs to know all this points. That's why I don't like it.
Currently I do the add / remove operations always on the server.

To be true it's a complete other point if we are talking about lists of primitives. A bidirectional binding that binds a list of String or number won't be a problem at all.

**Comment by netopyr** [comment]
There are use cases that are greatly simplified with bidirectional bindings, and that do not require you to create DolphinBeans on the client. For example we want to allow the user to change the order of existing objects. Changing a list on the client is already possible today, a bidirectional binding to a JavaFX List just simplifies it and makes the API more consistent.

I do not recall an explicit decision to never create Dolphin Beans on the client. So far we tried to avoid it, because it greatly simplifies the flow of events. But I am not really convinced that we can avoid this completely.

Removing orphan Dolphin Beans should not be a problem once we have GC.

**Comment by hendrikebbers** [comment]
@netopyr I think we can close this one
