### ISSUE TITLE
Update dependencies to latest versions

### ISSUE THREAD

**Issue by aalmiray** [canoo/dolphin-platform#139]
The following is a report of dependencies as of 28.04.2016

    The following dependencies have later milestone versions:
     - com.google.code.gson:gson [2.6.1 -> 2.6.2]
     - com.google.guava:guava [18.0 -> 19.0]
     - com.kumuluz.ee:kumuluzee-cdi [1.0.0 -> 2.0.0]
     - com.kumuluz.ee:kumuluzee-core [1.0.0 -> 2.1.0-beta.1]
     - com.kumuluz.ee:kumuluzee-servlet-jetty [1.0.0 -> 2.1.0-beta.1]
     - javax.enterprise:cdi-api [1.1 -> 2.0-EDR1]
     - javax.servlet:javax.servlet-api [3.1.0 -> 4.0.0-b01]
     - org.apache.deltaspike.core:deltaspike-core-api [1.3.0 -> 1.6.1]
     - org.apache.deltaspike.core:deltaspike-core-impl [1.3.0 -> 1.6.1]
     - org.glassfish:javax.el [3.0.0 -> 3.0.1-b08]
     - org.hibernate:hibernate-validator [5.1.3.Final -> 5.3.0.Alpha1]
     - org.jmockit:jmockit [1.16 -> 1.23]
     - org.open-dolphin:dolphin-client [1.0-RC1 -> 1.0-RC3]
     - org.open-dolphin:dolphin-combined [1.0-RC1 -> 1.0-RC3]
     - org.open-dolphin:dolphin-server [1.0-RC1 -> 1.0-RC3]
     - org.open-dolphin:dolphin-shared [1.0-RC1 -> 1.0-RC3]
     - org.slf4j:slf4j-api [1.7.10 -> 1.7.21]
     - org.springframework.boot:spring-boot-starter-web [1.2.2.RELEASE -> 1.3.3.RELEASE]
     - org.testng:testng [6.8.21 -> 6.9.11]

**Comment by netopyr** [comment]
OpenDolphin 1.0-RC3 contains a bug which prevents us from updating to the current version.

**Comment by hendrikebbers** [comment]
gson -> ok
guava -> ok
kumuluzee -> Ok if this is working with the current cdi & servelt version
cdi -> I think we should not update since the current version is the official JavaEE 6 version
servlet-api -> I think we should not update since the current version is the official JavaEE 6 version
delta-spike -> Ok if this is working with the current cdi version
org.glassfish:javax.el ->  I think we should not update since the current version is the official JavaEE 6 version
hibernate-validator -> Ok - maybe to a never version that is not an alpha ;)
org.jmockit:jmockit -> ok
open-dolphin -> will be migrated to DP
slf4j-api -> ok
spring-boot-starter-web -> ok, but we need to check a lot of transitive dependencies in this case
org.testng -> ok

**Comment by hendrikebbers** [comment]
@aalmiray Since you updated several dependencies this issue can be closed. Do you testet the Spring, JavaEE and Kumuluz servers after the update since we changed dependencies for all 3 (Spring, DeltaSpike & Kumuluz)

**Comment by aalmiray** [comment]
I'd rather have this issue still open as I couldn't get a working todo-example, even with 0.8.6 and no changes

**Comment by hendrikebbers** [comment]
Uh, that worked for me. Tried all combinations (JavaEE in JBOSS). Only KUmuluz is still broken at my PC.

**Comment by jermsam** [comment]
Hello Hendrik Ebbers. 
For some reason, I am not able to get started with Open Dolphin. All options , including jumpstart are failing. Even on my IDE [Eclipse] they project shows up with errors even after downloading all the required dependencies. What could be the problem?

**Comment by hendrikebbers** [comment]
@jermsam can you please add such an error.  What is exactly the problem? Do you opened the project as a Maven project in eclipse?
