### ISSUE TITLE
Implement a easy reconnect functionality for JavaFX

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#221]
Currently it's quite hard to implement a reconnect based on #211 and #213. The branch "reconnect-sample" already contains some ideas how this can be solved but #213 is needed for this. In addition #200 must be merged since we need to change something in the ClientConnector to do a real disconnect.

**Comment by davidyee** [comment]
While the reconnect feature works to establish a new connection from the client back to the server, changes to the client state (e.g. modifications to dolphin beans, user progress through forms, etc.) are lost. Is there a way to reconnect to a previously established session so that the client state is restored?

**Comment by hendrikebbers** [comment]
Hi @davidyee the plan is to do it like this:

the server will hold the state for some time. If the client reconnects in that time frame the old state will be reused. This means that nothing happens in that time on the client (otherwise you would have a conflict). After a specified timeout the server will destroy the session and only a new connection is working.

**Comment by hendrikebbers** [comment]
To make this clear: this behavior is not part of DP at the moment. That is what we want to have for version 1.0
