### ISSUE TITLE
how can i use open dolphin with spring data

### ISSUE THREAD

**Issue by mostfa-ayad** [canoo/dolphin-platform#349]
hi 
i want to save my data in the database
is my model  can be the same entity for spring data

**Comment by hendrikebbers** [comment]
Hi,

you need to create model classes for the entities (for example JPA) and for the Dolphin Platform model. A lib like http://mapstruct.org can help you to convert between the 2 types

**Comment by davidyee** [comment]
MapStruct is an interesting library. However, since [`Property`](http://www.dolphin-platform.io/javadoc/latest/java-core/com/canoo/dolphin/mapping/Property.html) fields requires creation of the presentation models via [`BeanManager#create`](http://www.dolphin-platform.io/javadoc/latest/java-core/com/canoo/dolphin/BeanManager.html#create-java.lang.Class-), is there a more suitable way to map JPA models into the Dolphin Platform models? As far as I can tell it is not possible to access the `BeanManager` through the mapper interfaces that you would create for MapStruct.

As you can see in the below MapStruct example of the user-specified mapper interface and the resulting generated mapper implementation, the conversion to their DTO is trivial because the object is simply instantiated via the new keyword. The mapped fields are then set accordingly. However, to do like-wise with a Dolphin Platform model would require access to the BeanManager.

```
@Mapper(componentModel = "cdi")
public interface CarMapper {
    Car carDtoToCar(CarDto carDto);
}
```

```
//GENERATED CODE
@ApplicationScoped
public class CarMapperImpl implements CarMapper {

    @Override
    public Car carDtoToCar(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        Car car = new Car();

        car.setOwner( ... );
        // more setters ...

        return car;
    }
}
```
