### ISSUE TITLE
Define a parent-child-relationship between controllers

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#382]
At the moment all controllers are managed objects in the server and do not know anything from each other. But sometimes you have master-detail or parent-child constellations where it would make sense to add the functionality to access a child or parent controller.

**Comment by hendrikebbers** [comment]
This image shows a basic workflow of the controller relationship. As you can see in the image the view and model instances should not know each other:
<img width="797" alt="access" src="https://cloud.githubusercontent.com/assets/9443847/23451415/21c2a9d0-fe60-11e6-90b1-d793f36a76f3.png">

**Comment by hendrikebbers** [comment]
On the server side the API to communicate with a parent or child controller might look like this:

Parent controller that wants to access it's child controller(s):

```
@DolhinController
public class MasterController {

    @DolphinModel
    private MasterBean model;

    @ChildControllerCreatedListener
    private void onDetailControllerCreated(DetailController c) {...}

    @ChildControllerDestroyedListener
    private void onDetailControllerDestroyed(DetailController c) {...}

}
```

In this API you can define `0..n` listener methods that will be called once a controller is created as a child controller of this controller. In addition you can add `0...n` listener that will be fired once a child controller will be destroyed. Each method must have one parameter that defines the controller type / class. By doing so a developer can provide several methods / listeners for several possible child types. In addition this should support abstract controller classes and / or interfaces.

Next to this it must be possible to access the parent controller from a child controller. The following class gives an example how this might look like:

```
@DolhinController
public class MasterController {

    @DolphinModel
    private MasterBean model;

    @ParentController
    private MasterController parent;

}
```

In this case the parent will be inject like any other managed object. Here a concrete controller type or an interface can be specified.

Based on this we can communicate in booth directions. In addition a developer do not need to define additional module dependencies since we can work with interfaces and only provide a dependency between the classes in one special direction (child knows parent / parent knows child)

**Comment by hendrikebbers** [comment]
To provide the described API on the server the Dolphin Platform must know about the hierarchy of controls. Since the entry point to create a MVC group is always the client view the Dolphin Platform must offer an additional / different API on the client.
At the moment all mvc groups are created by creating a controller proxy on the client. To create such a proxy the client context provide a factory method. The following code snippet shows how such a controller proxy can be created:

`ControllerProxy myControllerProxy = clientContext.createController("MyController");`

This client side code will create a new controller instance on the server and a model that is synchronized between client and server. 

Since all controller (proxy) instances are created by the clientContext no hierarchy is defined here.

**Comment by hendrikebbers** [comment]
Based on this the we need to change the public client API. My idea is to use the `createController(...)` method of the client context to only create so called root controllers that do not have a parent. If such a controller on the server side tries to inject a parent controller the field value will be `null`. Here is an example how such a root controller will be created:

ControllerProxy searchPageControllerProxy = clientContext.createRootController("SearchPageController");

I would deprecate the `createController(...)` method and add the `createRootController(...)` method. Internally `createController(...)` will call `createRootController(...)` and will be removed for version 1. This will help developers to do a migration of the API in future.

In addition the controller proxy will get a new method to create a child controller. Based on this you can create a controller hierarchy. Here is a sample how the API would look like:

```
ControllerProxy searchFilterControllerProxy = searchPageControllerProxy.createChildController("SearchFilterController");

ControllerProxy searchResultControllerProxy = searchPageControllerProxy.createChildController("SearchResultController");
```

The code will create a `SearchFilterController` and a `SearchResultController` instance on the server. Booth will be child controllers of the `SearchPageController` instance that was created by using the client context. On the server the client controllers could inject the root controller and listeners for adding / removing a child controller will be fired in the root controller.

**Comment by aalmiray** [comment]
1st: TooManyAnnotationsException. This is the CDI/JavaEE way.
2nd: what's important IMHO is expression the relationships between MVCs in such a way that's clear that ParentA has a strict relationship with ChildB and ChildC. The current proposal allows

    ControllerProxy myControllerProxy = clientContextA.createController("MyControllerD");
 
which will make the code fail catastrophically on the server if MyControllerD is written as

    public class MyControllerD {
        @ParentController private ParentControllerE parent;
    }

Notice that ChildD expects ParentE but we told the client that ParentA could create ChildD.

Why is this the case? because the creation mechanism is "stringy" typed in Java. We could create a "type safe" version ofr Java but will have to revert back to stringified types in JS anyway. *le sigh*.

**Comment by hendrikebbers** [comment]
@aalmiray About the annotations: Here we have different opinions. I think that most Java enterprise developers are familiar with such an API and want it
About the functionality: Yes, the point that you mentioned is a big problem that I see, too. I thought about simply injecting `null` in that case but it feels not right. Only providing a dependency the other way (listeners on parent) will always work but I do not know if this is enough. Maybe we can start with this feature (parent -> child relationship)

**Comment by aalmiray** [comment]
Honestly I think we have a problem of semantics. The discussion is geared towards MVCs but the API describes controller hierarchies. Something is not right.

The way we currently fake MVC hierarchies in our internal project is by using events between specific controllers. We do this in order to add/remove elements on a parent Model, these elements are created/updated by the child Model. In this particular case we know there's a parent-child relationship between the two controllers but we do not directly exploit it as we actually care more about the parent-child relationship between the models.

I'd rather see an API from the client's POV that dealt with MVCs instead of just Controller.

**Comment by hendrikebbers** [comment]
@aalmiray can you give an example with some "fake code snippets"? Currently I do not know how such an API should look like.

**Comment by hendrikebbers** [comment]
... and yes, sometimes I talk about MVC groups but this API is about controller hierarchies / relations. Let's not call my approach "MVC something". It's "Controller hierarchies".

**Comment by aalmiray** [comment]
I can't give you a sample API as the problem lies in the concept. Writing code at this point is too far down the line. The usage of model hierarchies I gave is a very concrete one. In this particular case the application requires 2 models to communicate with each other by having a parent/child relationship. It's assumed that the owning controllers of both models are also engaged in a parent/child relationship _because_ of the intrinsic nature of controller/model as established by DP.

As you see, even though the parent/child relationship may be expressed (so far) through pseudo code via controllers, applications will require to have parent/child relationships between Cs and Ms, hence why the MVC group notion arises. Granted, on the server side there's no V, but remember that the "group" is visible from the client side, as the full MVC is split between client and server.

**Comment by aalmiray** [comment]
re: annotations. See http://www.annotatiomania.com/ by Antonio Goncalves, well known and respected JavaEE advocate. While a tongue-in-cheek example it shows that overuse of annotations is something you should worry about.

Let's put it this way. If you can describe behavior using an specific contract, then put it in an interface. This is how the spring framework has evolved since the beginning, proving to be a rock solid foundation. Yes, Spring supports annotations, and yes it does use annotations to inject behavior to your custom classes.

Annotations such as @Transactional are quite generic. you can apply it to any piece of code that may require the use of transactions, not just controller methods. @Controller denotes a component that sports a very specific behavior in the web stack. then you pop the hood and see that it's just a meta-annotation that denotes "something" that behaves like a controller; and so does @Service. As a matter of fact the only difference between @Controller and @Service is their name! But the spring framework takes the semantic cue and performs different operations with the annotated class.

Now, and annotation like  @ChildControllerCreatedListener is way too specific. It would be better to provide a ControllerLifecycleListener interface for example, that the root/parent controller could implement instead. More over, what happens when a parent controller is disposed/destroyed? all child elements must be destroyed too, correct? Does the order of destruction matter? Does it make sense to notify some other component(s) when that happens?

Same goes for @ParentController. It's too constrained. It works for controller only and denotes a relationship from child to parent. But what about parent-child relationships between models? Do we need explicit parent-child relationships in models such that you could potentially define a `@Parent private RootModel parent` field on a child model? do we rely on the fact that controllers have a one-to-one association with models, so that the root model is the parent of the model of any child controller that's a direct (1 generation) descendant of the root controller? Let's go one step further and create a 1nd generation. Now you have RootController (grandfather), ChildController (father), BabyController (child).

BabyController can see ChildController if it has a matching filed annotated with @Parent. What about seeing RootController? Does it make sense to access it directly or does it have to navigate the hierarchy? Same goes for the model. And before you tell me there's the need of 1 generation access only let me remind you that our internal project has at least a 5 generation layout at the very least.

**Comment by hendrikebbers** [comment]
Yeah, I know annotatiomania but to be true I think that we have a different case here. In JEE you can really end in annotation hell if you have a pojo for JPA, JBV & Serialization ;) But in this case we have a specific method that is annotated with one additional annotation. I'm with you that the annotation is very special and maybe this is not the best solution.

Let's a look at a different possibility that I tried:

Using an Interface:
We are doing this a lot in DP when it makes sense. One example is the DolphinSessionListener (https://github.com/canoo/dolphin-platform/blob/master/platform/dolphin-platform-server/src/main/java/com/canoo/dolphin/server/DolphinSessionListener.java) because in this case it's easy to define an interface that matches all the needs. For the controller relation this is not useable. It was my first idea but at the end it creates some problems. Let's think about the following interface:

```
interface ControllerChildListener<T> {

    void childAdded(T childController);

    void childRemoved(T childController);
}

```
This looks good at the first moment and it is useable as long as a controller has only children of one class type. Since a controller can have sub controllers of any type you are loosing generic information and you could only use an interface like this:

```
interface ControllerChildListener {

    void childAdded(Object childController);

    void childRemoved(Object childController);
}
```

In this case we will end in 2001 cast hell.

So based on this I think that interfaces are not the right solution for the problem.


At the moment I still think that annotations are the way to go. Maybe the current API / definition is not that good. I'm fine. So let's start thinking about what we want to have at the end:

* A controller must be notified when a child controller is created (high priority issue)
* A controller must be notified when a child controller is destroyed (important to avoid memory leaks - holding old child controller instances as local var)
* A controller must access it's parent (currently this is not really needed since everything could be done by the first 2 features, so this is nice to have)

If we only look at the 2 first points there are some open questions:
* If a controller will be destroyed, should all childs be destroyed, too?
* Is the listener only be fired for direct children or for all children?
* How can a controller access a baby controller? - love that naming 😂 

I do not think that destroying a controller should automatically destroy all child controllers. This should always be triggered by the view (calling destroy on controller proxy) or a timeout (like session timeout). In several scenarios a child view could be externalized in a extra window and maybe you than close the main window. There are several scenarios in that such an automatically destruction of the hierarchy would end in problems. On the other this means that a "parent controller" could be null since the view was already removed. This is again a point that destroys my first idea of injecting the parent in the client. If the parent knows the child he could simply pass itself to the client controller and creating a memory leak by doing so (no weak ref in client and parent controller will be removed). But to be true you can end in such an scenario in mostly every framework (like holding closed window instances in Swing or JavaFX).

About accessing the baby controller: To be true I would not provide an API for that. If you need such an hierarchy I would add methods in the controllers. I understand your point but when having a look at UI toolkits it's mostly the same (if you do not use a lookup method).

About using events / an event bus: Here I do not see how we can really define the right instance. Think about an application that works like a browser and can have several taps with application views. In that case you could have several instances of the same type in one client. Based on this I do not know how a event based system should be defined to solve this problem.

**Comment by hendrikebbers** [comment]
From my point of view annotations at the listener methods are more like the annotations of JAX-RS (sample: http://www.mkyong.com/webservices/jax-rs/jax-rs-path-uri-matching-example/).

**Comment by hendrikebbers** [comment]
The WebSocket JSR is doing more or less the same: https://docs.oracle.com/javaee/7/api/javax/websocket/OnOpen.html

**Comment by hendrikebbers** [comment]
Good overview of listeners in Spring: https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2

This goes more in the direction that @aalmiray is thinking (as far as I see it). But the difference is that such event listeners are defined for "global" events. I think it's hard to define such an API for hierarchies.

**Comment by aalmiray** [comment]
Not really, no. Spring application events are too low level. Spring came to this discussion in terms of general API design and guidelines. when discussing an event bus I'm thinking in an API inspired by MBassador https://github.com/bennidi/mbassador

I do believe that as a guideline, the destruction of a parent controller should take down all of its children controllers. There's one exception, the use case mentioned of a "child" MVC moving out from its current containing "panel" into its own "window". This is akin to popping a panel from a docking manager into an external window. At any point the window can be closed, in which case the content may be:
 - reattached to its "original" container.
 - lost forever.
any of these two is possible depending on the use case. The platform should not force one or the other but allow for both to be chosen according to the application's requirements.

What's the use case for having a parent controller be notified by type that a child controller has been initialized? Does the parent controller expect to call a parent/child lifecycle method on the child? Does it need to perform some post initialization on the child's model? If so, can this post initialization happen on the child instead? Similar questions regarding destruction/predestroy.

This last point can be solved if controllers have a well defined lifecycle contract, such as `init()` and `destroy()`. One possibility to define such contract is to define an interface that all controllers must extend. this will for lifecycle methods to have a public visibility modifier. On the other hand you could provide the same behavior using a pair of private methods annotated with @ControllerInit and @ControllerDestroy (example names). Whay? because this contract should be invoked by DP at the right time and noone else. @PostConstruct and @PreDestroy might be used _if_and_only_if_ DP can ensure that all dependencies (including parent references) have been injected by the DI container at the right time. If DP can't assert that then a new pair of annotations (like the suggested ones) may be used. Or we go back to the interface with the aforementioned visibility caveat.

**Comment by hendrikebbers** [comment]
About @PostConstruct / @PreDestroy: This is already supported and we can ensure that all injectable fields are injected. DP provides support for Spring & CDI to do so. Based on this we don need something like @ControllerInit / @ControllerDestroy since this is already handled by @PostConstruct / @PreDestroy

**Comment by hendrikebbers** [comment]
Usecases:

* A master-detail-view in that the master (parent) set the selected value directly to the detail view (child controller). In this case the master controller needs to know the child controller. This can be done by a "child-controller-created" event
* A modal dialog that is opened to select some details. In this case the parent controller can pass pass information to the child controller (controller of the modal dialog). Once the dialog is closed the master controller can get the selected value of the modale dialog by using the "child-controller-destroyed" event.

In both cases the "child-controller-created" should be fired after a possible @PostConstruct method of the child controller. The "child-controller-destroyed" should be fired before the @PreDestroy method of the child controller is fired.

**Comment by aalmiray** [comment]
I did not say: DP must support @PostConstruct / @PreDestroy. I know DP already supports it. I did say: you need a way to establish the parent-child relationship. One way is to rely on @PostConstruct if and only if all requirements are set by the time the postconstruct method is invoked. Otherwise you need a second lifecycle, such as `init()` defined by a controller interface.

**Comment by hendrikebbers** [comment]
ok :)
I think the mentioned use cases can not be solved by using @PostConstruct / @PreDestroy.
Based on this we need an additional / different solution to provide relations between controllers.

**Comment by aalmiray** [comment]
Both the master-detail and parent-modaldialog scenarios can be solved using a shared context between the two actors. This is why I've been saying you don't start by writing pseudo code. Listener interface, annotations, shared context, all of them have pros and cons based on initialization, lifecycle and bookkeeping. There may be other strategies to solve the parent-child relationship.

The use cases are more important than the pseudo code at this point.

**Comment by hendrikebbers** [comment]
We need to find a way how this can be solved in JavaScript / HTML.

Example:

<parent-component>
    <child-component></child-component>
    <child-component></child-component>
</parent-component>

How should the controller proxy of the child components be created? They need to access the controller proxy of the parent component. At the moment in JS we use a global client context that can easily be accessed in all components.

**Comment by hendrikebbers** [comment]
For the start beginning we should define the Workflow like this:

If a parent controller (proxy) is destroyed all child controller (proxies) will be destroyed, too.

**Comment by hendrikebbers** [comment]
We need to decide if we want to use a event-listener based solution or a relation based solution.

**Comment by hendrikebbers** [comment]
We need to check how Angular / Polymer react on DOM changes
