### ISSUE TITLE
Use sun.misc.Unsafe internally to support Java 9

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#437]
I think we need to use sun.misc.Unsafe in the ReflectionHelper to get DP working with Java 9.

**Comment by blackdrag** [comment]
What exactly do you want to use it for? Unsafe will not let you go around the module system

**Comment by hendrikebbers** [comment]
Currently we use Method.setAccesible() and this can not be used in Java 9. See https://twitter.com/rafaelcodes/status/813519791025688576

**Comment by blackdrag** [comment]
If you want to use offsets to read fields for example, I would suggest writing a small example, where you do this on a non-public field form a class from a java module, for example on ClassLoader. Because this kind of usage if supposed to be done now by VarHandles http://openjdk.java.net/jeps/193. And I do not know out of the my head of they did enforce their module logic in Unsafe... but I would strongly assume so.

**Comment by hendrikebbers** [comment]
Ok, renamed the issue. This is more or less a reminder that we need to do something in future. We can discuss this later. Until now all my knowledge is based on reading blogs etc.. Never tried it with Java 9...
