### ISSUE TITLE
The initial connection request times out when starting DP JFx client with JWS.

### ISSUE THREAD

**Issue by janakmulani** [canoo/dolphin-platform#475]
When starting DP JFx client with JWS, there is a connection time out. It then asks to reconnect. Upon reconnection, the DP Fx Client is able to connect to the server and the app runs ok.

**Comment by hendrikebbers** [comment]
Does this still happens with the last sample?

**Comment by hendrikebbers** [comment]
@janakmulani ?

**Comment by hendrikebbers** [comment]
@janakmulani can I close this issue???
@kunsingh can you ask him? ;)

**Comment by hendrikebbers** [comment]
Added @kunsingh since @janakmulani is not answering...

**Comment by janakmulani** [comment]
Hendrik,

Sorry for delay in replying. This issue was faced when were trying integrating a DP FX app inside ULC Portal and where ULC Portal client was started using JNLP. 

Since this DP Fx integration into ULC Portal is not part of ULC release, this issue has been put on back burner. I have not had time to revisit this issue. 

I still have the test app somewhere. I am giving it to Kunal to try it and see if the issue can still be reproduced.

**Comment by kunsingh** [comment]
Unable to launch JNLP -
While Debugging I found followings :- 
- Service loader is not able to load all the classes and that's why its failing.
- Manifest.MF file is blank

To Debug- 
- Create a remote debug configuration in Idea
agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006
- gradle clean build - web-deployment-server and deploy war to Tomcat
- Start the Tomcat server
- open other terminal and go to Tomcat/Webapps/WebDeployement/fxclient
- export JAVAWS_VM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006
- javaws fxclient.jnlp 
- Start debug configuration in java

**Comment by kunsingh** [comment]
Fix depends on - https://github.com/canoo/dolphin-platform/issues/861
