### ISSUE TITLE
Handling of success/failures/errors on the client side

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#49]
When a client invokes a server action there may be 3 possible outcomes:
- success: action completes as expected.
- failure: server signals an error condition, such as validation failure.
- exception: an error occurred during transmission.

Currently it's impossible to handle the 2 later cases. OpenDolphin offers a general exception handler that may be used by DP to solve #61 but #30 remains.

Here's an idea of how DP could handle these cases on the client side

``` java
public void save() {
    controllerProxy.invoke('save')  //calls "save" action on the server controller
                   .onSuccess( s -> successNotification(CrudType.Create)) 
                   .onError( r -> errorNotification(CrudType.Create))
                   .onException( e -> /* oops */ )
                   .invoke();
}
```

**Comment by hendrikebbers** [comment]
The invoke method returns a CompleteableFuture<Void> that can be used to get notification about a server error (no message / stack trace). I think this is fine for the action invocation. Maybe we should think about some kind of interceptor on the server that can be used to add application specific exception handling.
@aalmiray What do you think?

**Comment by aalmiray** [comment]
Perhaps, however `CompletableFuture` is still one degree away from integration with DP, that is, you can receive a notification of failure/error but can't automatically distinguish between the two. By failure I mean an application error (such as validation) where as an error is a plumbing problem (network connection went down, OOM). Failures must be handled by server application code where as errors must be handled by DP's internals (think of a global uncaught exception handler).

If this is the case then a proper abstraction that differentiates between failures and errors is needed. That's the reasoning behind the API proposal (inspired in RxJava's `Observable` abstraction). It does not have to be implemented exactly that way but at the very least I'd expect a distinction between failures and errors.

**Comment by hendrikebbers** [comment]
mmh, understand what you mean. I think we should discuss this after 0.8 has been released

**Comment by aalmiray** [comment]
Perhaps https://github.com/jdeferred/jdeferred can be used instead of `CompletableFuture`. As far as I recall CF was used i the Java client because it's the closest thing to the "promise" behavior seen in JS. Given that JDeferred is inspired by JQuery's promise and Android's Deferred object I'd say this library delivers a better abstraction.

**Comment by netopyr** [comment]
I would not want to introduce a new class for several reasons.

1. CompletableFuture was inspired by Promises, too, and it contains all we need. I even consider it something like Promise 2.0, because it has additional functionality for simple, but usually sufficient, orchestration of several CompletableFutures. I do not see a need to switch to something else.

2. It adds another dependency.

3. It adds another step to the learning curve, because I doubt that many Developers are familiar with JDeferred. My expectation is, that in the near future more and more developers will already have encountered CompletableFuture. Even if not, the hurdle to study it will be lower, because it usually pays off to learn about a new standard JDK class, while the same is not true for third party components.

**Comment by hendrikebbers** [comment]
@kunsingh Please check and document the current state in JS

**Comment by hendrikebbers** [comment]
Currently default JavaScript promise is used here. See https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise

I think that a JS developer should be familiar with this. The big question is: Do we need additional support / functionality in JS. @netopyr what do you think?

**Comment by hendrikebbers** [comment]
@madmas what do you think about this issue? Maybe you can give us some feedback :)

**Comment by hendrikebbers** [comment]
@madmas PING PING 😆

**Comment by hendrikebbers** [comment]
@netopyr PING PING 😆

**Comment by netopyr** [comment]
Promises are sufficient and JS-developers are familiar with it. What other options do you have in mind?

**Comment by hendrikebbers** [comment]
Don't know ;) You are my Guru. If you say promises are the best for developers we can close this issue

Von meinem iPhone gesendet

**Comment by aalmiray** [comment]
This issue was mistitled. It's not just the JS client, but all clients. A promise can handle a single type of failure. 

The remoting layer also makes no distinction on the type of failure (semantic or plumbing/connection). At the very least the Java client can handle errors using a global error handler, which can't differentiate between failures and errors. No idea what the JS client can do in this case.

Thus, _if_ it's important to differentiate between failures and errors _then_ promises are not enough.

**Comment by hendrikebbers** [comment]
I know ;)
I will create a seperate Jave issue.

Errors (platform / remoting )will always stop the communication.
An exception on the server action should be reflected to the promise.



Von meinem iPhone gesendet

**Comment by hendrikebbers** [comment]
Issue for Java client: https://github.com/canoo/dolphin-platform/issues/408
