### ISSUE TITLE
View / Window Scope to support multiple browser tabs

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#50]
The solution will be based on a Dolphin-Session that is defined by a unique ID.

**Comment by Dierk** [comment]
Wait with this one. It needs more consideration.

**Comment by hendrikebbers** [comment]
@Dierk I will add my thoughts about this topic the next days.

**Comment by hendrikebbers** [comment]
From my point of view this problem is already solved by some web application frameworks. The trick is to create a new scope type that is part of the session. By default all tabs in a browser share a session. If you now want to define anything that is only specific for one tab you need to define a scope that is smaller than the session scope. This means that a session can hold several of this scope instances in parallel. Since the HTTP protocol can't simply handle such a feature a specific identifier is needed that defines a tab. Holding this identifier is quite easy because each tab has it's own JavaScript Sandbox. But synchronizing this identifier with the server is often a problem. This is very hard if you use several remoting types in an application like REST and WS. If the complete communication is wrapped by a remoting layer like in the Dolphin Platform this is quite easy. In this case the remoting layer can add the tab identifier as a param for each request header.
In addition it's important that an action is triggered whenever a tab is closed. If this won't happen the server has no idea when he can destroy the scope of the tab. As far as I know this can be handled by JavaScript in a general way (http://stackoverflow.com/questions/3888902/javascript-detect-browser-close-tab-close-browser / http://stackoverflow.com/questions/10311341/confirmation-before-closing-of-tab-browser).

Here are some links that document the feature for JavaEE, Spring, JSF and Vaadin:
*  http://stackoverflow.com/questions/13292395/how-to-store-data-for-every-individual-browser-tab-window-the-session-scope-is
*  http://stackoverflow.com/questions/4479995/managing-webapp-session-data-controller-flow-for-multiple-tabs/4480310#4480310
*  https://jaxenter.de/multi-browser-tab-support-in-java-ee-7-491
*  https://blog.oio.de/2013/02/22/vaadins-variable-scopes-vaadinsession-and-ui/
*  https://books.google.it/books?id=I2rzi5B7Y6oC&pg=PA91&lpg=PA91&dq=Java+Tab+scope&source=bl&ots=qTh917Jp-O&sig=vZrMmnN-zLdEYeUctbBm5vW1WZE&hl=de&sa=X&ved=0ahUKEwjKkbKr_sXKAhXHBSwKHaUaBGs4ChDoAQhRMAc#v=onepage&q=Java%20Tab%20scope&f=false
*  http://stackoverflow.com/questions/4244475/jsf-cdi-conversation-scope-beans-best-practice
*  https://books.google.it/books?id=Wh36a6zntX0C&pg=PT88&lpg=PT88&dq=Java+Tab+scope&source=bl&ots=Tks8DsKIMa&sig=bpzsZbGA1Lm1x3ENFWl28jL32b0&hl=de&sa=X&ved=0ahUKEwjKkbKr_sXKAhXHBSwKHaUaBGs4ChDoAQhfMAk#v=onepage&q=Java%20Tab%20scope&f=false
*  https://docs.jboss.org/weld/reference/2.1.2.Final/en-US/html/scopescontexts.html

I think it's important that all tabs still share the same session. By doing so a user don't need to relogin when he opens a new tab since the security informations are stored in a session. In addition general user data like the shopping cart informations of a webshop can be stored in the session and will automatically be shared between all tabs.

When talking about Dolphin Platform I think that we need something like a ClientScope (I don't like WindowsScope since we can have desktop clients). All Information of one server dolphin / model store are stored in the context of one ClientScope instance. If the user closes the window we can simply remove the context and it's content.

**Comment by hendrikebbers** [comment]
#121

**Comment by hendrikebbers** [comment]
resolved in #131

**Comment by hendrikebbers** [comment]
With 0.8.4 the server (JavaEE and Spring) is ready for this feature (see #131) . Changes / support in the client will come in the next version.
