### ISSUE TITLE
Check how we can define a good public / private API split in JS

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#591]
We have it in Java, how can we do it in JS?

**Comment by hendrikebbers** [comment]
Check of frameworks like REACT or Angular do it. Do they have private APIs?

**Comment by giftkugel** [comment]
The "private" API is now defined through Webpack. Webpack creates the lib for us.
With the next version the `platformClient` keyword/object will be introduced to the JavaScript client. The older `dolphin` keyword/object will still be accessible due to backward compatibility. So `dolphin.ClientContextFactory` will still be there but will show a deprecation warning.
