### ISSUE TITLE
Check how JS frameworks provide HTTP clients

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#592]
We are currently working on the Java HTTP client. This should happen in JS, too. Here we should check how other framework HTTP clients like REACT or Angular. Based on this we can decide how the JS vanilla HTTP client should look. In addition we can check if we can add specific integration in the Angular HTTP client for example.

**Comment by hastebrot** [comment]
There is the standardized `window.fetch` API from WHATWG for this. It aims to replace `XMLHttpRequest`, and it is `Promise`-based.

- Specification: https://fetch.spec.whatwg.org/
- Polyfill for older browsers: https://github.com/github/fetch

Example:

~~~js
fetch("/users.json")
  .then(response => response.json())
  .then(json => console.log("parsed json", json)
  .catch(error => console.log("parsing failed", error);
~~~

Integration in React should be simple. Angular uses it own `$http` and promise stuff; which should be ok, since we should not couple deep to specific APIs.

For another complete and modern HTTP client for browser and node see: https://github.com/axios/axios
