### ISSUE TITLE
Polymer: Use <test-fixture> in component tests.

### ISSUE THREAD

**Issue by hastebrot** [canoo/dolphin-platform#620]
Polymer 2.x uses `web-component-tester` 6.x [[1]] which bundles `<test-fixture>` 3.x [[2]].

[1]: https://github.com/Polymer/web-component-tester/releases
[2]: https://github.com/PolymerElements/test-fixture/releases

`<test-fixture>` provides a simple way to test web components. It attaches and detaches elements before and after a single test case.

~~~html
<test-fixture>
  <template>
    <my-dolphin-element />
  </template>
<test-fixture>
~~~

We should define a standard way to use dolphin controller for test fixtures that considers the life-cycle of test-fixtures/dolphin-controller <s>, i.e. an attached element should connect to a controller, and a detached element should disconnect from the controller.</s>

Currently we use JavaScript code within a `<script>` element to connect to the <s>Dolphin controller</s> Dolphin server via connection context. Probably we should introduce a new `<dolphin-controller>` element in order to define the controller declaratively.

**Update:** Clarify sentences (Dolphin connection and Dolphin controllers).

**Comment by hendrikebbers** [comment]
I think you are mixing the connection context (1 per client) and the controller (1 per view, can be N per client) here.
Providing an element for the context / the connection makes sense

Von meinem iPhone gesendet

**Comment by hastebrot** [comment]
Right. AFAIK the connection context is globally defined and runs the whole time to push/poll changes from the server. Custom elements need access to the connection context.

~~~js
Polymer({
        is: "my-view",
        behaviors: [clientContext.createBehavior('MyController')]
})
~~~

>Providing an element for the context / the connection makes sense

I wonder what's the right approach. If we use a `<dolphin-connection>` element how can `<my-view>` access the connection. Dolphin provides an event bus, maybe we could use it.

This is also interesting, if we want to test `<my-view>` without an dolphin connection, i.e. a connection the a server. Maybe we could provide a `<dolphin-controller>` elements, that knows how to access the `<dolphin-connection>` and is used this way:

~~~html
<my-view>
  <dolphin-controller name="MyController">
<my-view>
~~~

For tests we could replace `<dolphin-controller>` with `<dolphin-controller-mock>`.

**Comment by hastebrot** [comment]
To clearify the concepts:

- Attaching/detaching a `<dolphin-connection>` element means we connection/disconnect to/from a dolphin server.
- Attaching/detaching a `<dolphin-controller>` element means we poll/push changes to/from the dolphin controller.

**Comment by hendrikebbers** [comment]
I think this will not work. According to https://github.com/canoo/dolphin-platform/issues/382 you can have a hierarchy in the controller.

When you have a web view (like index.html) you will have something like this:


```
<my-custom-view-1></my-custom-view-1>

<my-custom-view-2></my-custom-view-2>
```

In this case both views are polymer web components and both should connect to a controller on the server and share a model with the controller. To do so the components needs to know the connection and the name of the controller. The name of the controller should be part of the polymer components as it is today (so in my-custom-view-2.html for example).

For the connection it would be perfect if it can be passed to the component:

`<my-custom-view-2 connection=myDolphinConnection></my-custom-view-2>
`

In this case a mixing could handle everything. Based on this it is only important that we pass the connection to the component.

When we have hierarchies it is more complex since a sub controller must be created from the parent controller. In that case the following code will not be enough:

`<my-custom-view-2 connection=myDolphinConnection></my-custom-view-2>
`

The good point is that controllers are always created the same way:

`provider.createController("NameOfTheController");
`

In this case the `provider` can be the connection (to create a top level controller) or a controller (to create a child).

Since the method is the same we can maybe define it like this:

`<my-custom-view-2 controllerProvider=XYZ></my-custom-view-2>
`
In that case the `controllerProvider` can be the connection context or a controller. The mixing will internally handle this and create automatically the controller proxy once the web component is created.

Let's say we create a component for the context / connection. This would look like this in the main level (index.html):

`<dolphinClientContext endpoint="http://localhost:8080/dolphin"></dolphinClientContext>
`

This component now wraps the connection internally in an attribute. When we create a new view the connection must be passed:

`<my-custom-view-2 controllerProvider=THE_CONNECTION></my-custom-view-2>
`

Here the big problem is how we can pass the connection of the `dolphinClientContext` component to the view component.

If we want to create a sub component it will be more easy. Since the mixing creates and handles the controller proxy we can simply create a sub component in a component like this:

`<my-sub-view controllerProvider=controller></my-sub-view>
`

**Comment by hastebrot** [comment]
Closing. This is implemented in the current Polymer client.
